In [3]:
import csv
import pandas as pd
import random
from collections import OrderedDict

In [5]:
data = pd.read_csv('dataset', header=None)

In [4]:
data.shape

(197324, 600)

In [6]:
L = 8

In [7]:
def sub_table(L, view):
    m = data.shape[0] # or smaller number 
    sub_origin_table = data[data.columns[view]].sample( n = m ) # select the view attributes from original dataset
    return sub_origin_table

In [29]:
# generate all the permutation of 0,1 in size m  (string)
permutation_number = (1<<L)-1
permutations = []
for i in range(permutation_number+1):
    fo = '0' + str(L) + 'b' # format length
    number = format(i, fo ) # change to binary concat
    permutations.append(number)
    
print(permutations)

['00000000', '00000001', '00000010', '00000011', '00000100', '00000101', '00000110', '00000111', '00001000', '00001001', '00001010', '00001011', '00001100', '00001101', '00001110', '00001111', '00010000', '00010001', '00010010', '00010011', '00010100', '00010101', '00010110', '00010111', '00011000', '00011001', '00011010', '00011011', '00011100', '00011101', '00011110', '00011111', '00100000', '00100001', '00100010', '00100011', '00100100', '00100101', '00100110', '00100111', '00101000', '00101001', '00101010', '00101011', '00101100', '00101101', '00101110', '00101111', '00110000', '00110001', '00110010', '00110011', '00110100', '00110101', '00110110', '00110111', '00111000', '00111001', '00111010', '00111011', '00111100', '00111101', '00111110', '00111111', '01000000', '01000001', '01000010', '01000011', '01000100', '01000101', '01000110', '01000111', '01001000', '01001001', '01001010', '01001011', '01001100', '01001101', '01001110', '01001111', '01010000', '01010001', '01010010', '01010011', '01010100', '01010101', '01010110', '01010111', '01011000', '01011001', '01011010', '01011011', '01011100', '01011101', '01011110', '01011111', '01100000', '01100001', '01100010', '01100011', '01100100', '01100101', '01100110', '01100111', '01101000', '01101001', '01101010', '01101011', '01101100', '01101101', '01101110', '01101111', '01110000', '01110001', '01110010', '01110011', '01110100', '01110101', '01110110', '01110111', '01111000', '01111001', '01111010', '01111011', '01111100', '01111101', '01111110', '01111111', '10000000', '10000001', '10000010', '10000011', '10000100', '10000101', '10000110', '10000111', '10001000', '10001001', '10001010', '10001011', '10001100', '10001101', '10001110', '10001111', '10010000', '10010001', '10010010', '10010011', '10010100', '10010101', '10010110', '10010111', '10011000', '10011001', '10011010', '10011011', '10011100', '10011101', '10011110', '10011111', '10100000', '10100001', '10100010', '10100011', '10100100', '10100101', '10100110', '10100111', '10101000', '10101001', '10101010', '10101011', '10101100', '10101101', '10101110', '10101111', '10110000', '10110001', '10110010', '10110011', '10110100', '10110101', '10110110', '10110111', '10111000', '10111001', '10111010', '10111011', '10111100', '10111101', '10111110', '10111111', '11000000', '11000001', '11000010', '11000011', '11000100', '11000101', '11000110', '11000111', '11001000', '11001001', '11001010', '11001011', '11001100', '11001101', '11001110', '11001111', '11010000', '11010001', '11010010', '11010011', '11010100', '11010101', '11010110', '11010111', '11011000', '11011001', '11011010', '11011011', '11011100', '11011101', '11011110', '11011111', '11100000', '11100001', '11100010', '11100011', '11100100', '11100101', '11100110', '11100111', '11101000', '11101001', '11101010', '11101011', '11101100', '11101101', '11101110', '11101111', '11110000', '11110001', '11110010', '11110011', '11110100', '11110101', '11110110', '11110111', '11111000', '11111001', '11111010', '11111011', '11111100', '11111101', '11111110', '11111111']

In [31]:
total_view = []

def generating_counting_matrix(L):
    # random select attribute as a view
    attributes = range(data.shape[1]) # All the attributes in the dataset
    view = random.sample(attributes,L) # randomly select m attributes
    view = sorted(view)
#     print(view)
    total_view.append(view)
    
    # sub_sampling from the original data
    sub_origin_table = sub_table(L, view)
    mapping_row_to_binary = sub_origin_table.T.to_dict('list')
    
   

    dictOfCount = { i:0 for i in permutations}
    for x,y in mapping_row_to_binary.items():
        binary_to_string = ''.join(map(str, y)) # change v in k,v to string of binary
        dictOfCount[binary_to_string] = dictOfCount.get(binary_to_string,0) + 1 # update count
    return pd.DataFrame(list(dictOfCount.items()), columns = ['permu',view]).T.iloc[[1]]

In [32]:
result = generating_counting_matrix(L)

In [28]:
for i in range(2):
    sample = generating_counting_matrix(L)
    result = result.append(sample)

In [15]:
result

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
"[16, 99, 104, 168, 252, 302, 367, 407]",91,8,31,2,5,0,2,0,27,3,...,927,216,9479,3271,3055,1143,2458,846,930,463
"[154, 178, 281, 296, 417, 505, 565, 590]",24127,2430,2576,334,1604,169,282,36,4869,741,...,182,70,582,266,308,163,137,65,98,221
"[80, 184, 233, 243, 357, 383, 458, 559]",5321,238,1639,41,910,53,286,9,2210,66,...,1596,59,2894,134,6227,271,2173,106,5316,396

In [30]:
total_view

[[42, 78, 105, 228, 282, 480, 524, 552],
 [300, 315, 338, 379, 406, 501, 543, 582],
 [25, 86, 191, 463, 508, 514, 547, 555]]

In [15]:
result.to_csv('./counting_matrix.csv', header = None)

In [16]:
df_index= pd.DataFrame(total_view)

In [18]:
df_index.to_csv('./selected_attribute.csv',header = None)

In [34]:
np.random.laplace(3)

3.235910718858621

In [47]:
def generate_attribute_list(num_attrs,marginal_size,num_margianl_tables):
    marginal_attrs = []
    attrs = []
    all_attributes = range(num_attrs)
    for i in range(num_margianl_tables):
        attr = random.sample(all_attributes, marginal_size)
        marginal_attrs.append(attr)
        attrs = attrs+attr
    print(len(set(attrs)))
    return marginal_attrs

In [48]:
generate_attribute_list(600,8,100)

421

[[97, 150, 292, 296, 265, 0, 340, 139],
 [335, 513, 127, 330, 308, 109, 292, 263],
 [481, 76, 409, 194, 142, 23, 407, 196],
 [597, 23, 183, 265, 49, 310, 69, 42],
 [463, 424, 218, 28, 359, 271, 27, 25],
 [465, 423, 309, 393, 202, 289, 522, 232],
 [437, 282, 72, 400, 94, 427, 591, 286],
 [260, 367, 346, 469, 101, 57, 538, 526],
 [410, 266, 94, 184, 152, 107, 172, 194],
 [120, 86, 212, 352, 0, 177, 24, 176],
 [563, 398, 165, 26, 191, 152, 235, 159],
 [63, 10, 510, 32, 370, 27, 317, 211],
 [452, 429, 501, 457, 165, 219, 362, 268],
 [86, 311, 208, 274, 502, 39, 519, 177],
 [491, 215, 598, 513, 500, 355, 332, 261],
 [492, 425, 437, 128, 444, 254, 119, 19],
 [36, 239, 8, 438, 381, 384, 115, 352],
 [198, 230, 127, 29, 337, 271, 135, 342],
 [487, 529, 167, 385, 119, 523, 93, 150],
 [59, 408, 581, 514, 65, 452, 473, 538],
 [381, 557, 185, 437, 350, 571, 329, 346],
 [561, 192, 534, 73, 589, 529, 25, 421],
 [431, 186, 73, 239, 580, 469, 26, 543],
 [265, 299, 426, 3, 480, 526, 485, 223],
 [421, 289, 77, 85, 550, 441, 210, 190],
 [530, 153, 324, 346, 457, 104, 419, 391],
 [402, 262, 8, 576, 393, 396, 176, 267],
 [520, 100, 436, 352, 579, 591, 125, 99],
 [575, 381, 225, 448, 173, 450, 261, 59],
 [56, 125, 82, 406, 596, 507, 363, 417],
 [222, 508, 244, 343, 143, 271, 16, 154],
 [23, 94, 69, 121, 570, 455, 117, 572],
 [567, 398, 435, 303, 0, 185, 338, 82],
 [536, 8, 85, 149, 147, 424, 45, 381],
 [401, 199, 517, 308, 530, 41, 375, 443],
 [500, 118, 272, 424, 297, 409, 594, 430],
 [479, 259, 22, 539, 326, 592, 512, 278],
 [592, 574, 474, 232, 190, 65, 270, 304],
 [11, 70, 9, 439, 30, 262, 34, 61],
 [207, 101, 81, 318, 159, 73, 388, 518],
 [276, 586, 295, 64, 336, 182, 565, 427],
 [578, 576, 172, 44, 423, 239, 101, 232],
 [174, 304, 79, 338, 64, 236, 561, 11],
 [567, 510, 106, 125, 361, 314, 66, 146],
 [421, 239, 504, 64, 410, 1, 89, 400],
 [86, 288, 222, 93, 213, 398, 361, 594],
 [415, 109, 236, 20, 328, 497, 8, 295],
 [416, 496, 110, 198, 316, 338, 104, 38],
 [474, 94, 583, 533, 283, 143, 130, 54],
 [204, 28, 452, 94, 352, 281, 504, 534],
 [566, 207, 5, 187, 136, 45, 65, 567],
 [99, 552, 215, 115, 242, 261, 187, 66],
 [396, 51, 296, 353, 217, 524, 319, 244],
 [47, 485, 281, 260, 70, 524, 433, 128],
 [362, 238, 151, 194, 251, 95, 104, 55],
 [234, 315, 245, 347, 328, 429, 501, 444],
 [304, 110, 331, 128, 588, 485, 287, 299],
 [312, 372, 488, 316, 520, 105, 190, 319],
 [260, 154, 38, 460, 199, 396, 380, 473],
 [425, 338, 60, 283, 311, 500, 228, 473],
 [308, 232, 319, 184, 576, 548, 547, 1],
 [138, 452, 183, 352, 488, 230, 568, 245],
 [251, 177, 241, 83, 593, 190, 131, 188],
 [355, 468, 83, 485, 121, 43, 597, 418],
 [199, 218, 223, 397, 301, 361, 5, 439],
 [163, 200, 403, 560, 86, 380, 8, 406],
 [73, 80, 422, 483, 298, 390, 523, 26],
 [525, 184, 436, 488, 303, 399, 8, 49],
 [484, 91, 188, 282, 243, 151, 363, 488],
 [489, 209, 15, 337, 473, 27, 47, 385],
 [121, 9, 555, 366, 132, 388, 434, 573],
 [221, 597, 108, 83, 339, 252, 263, 129],
 [200, 207, 390, 484, 227, 324, 488, 533],
 [550, 532, 176, 173, 243, 469, 264, 159],
 [72, 196, 235, 466, 110, 179, 321, 458],
 [453, 483, 163, 45, 215, 515, 153, 528],
 [34, 431, 17, 433, 138, 288, 562, 254],
 [432, 523, 261, 247, 117, 564, 594, 140],
 [308, 368, 164, 520, 47, 99, 565, 128],
 [465, 442, 427, 390, 441, 101, 281, 91],
 [195, 454, 46, 452, 106, 105, 135, 299],
 [3, 460, 40, 574, 327, 506, 11, 233],
 [299, 103, 56, 140, 68, 582, 405, 352],
 [509, 479, 143, 329, 408, 414, 502, 102],
 [74, 300, 526, 350, 579, 182, 477, 179],
 [534, 249, 473, 489, 461, 66, 340, 294],
 [596, 342, 594, 233, 151, 589, 508, 327],
 [238, 565, 514, 494, 517, 116, 37, 429],
 [475, 339, 593, 273, 86, 469, 465, 89],
 [370, 461, 329, 154, 165, 119, 301, 559],
 [474, 131, 469, 384, 32, 579, 349, 391],
 [532, 586, 510, 424, 578, 21, 125, 236],
 [333, 23, 134, 108, 289, 278, 295, 58],
 [367, 181, 561, 211, 121, 14, 132, 154],
 [430, 132, 247, 385, 168, 80, 138, 355],
 [388, 109, 24, 58, 518, 177, 93, 240],
 [79, 264, 93, 342, 481, 578, 8, 510],
 [168, 75, 68, 236, 159, 163, 286, 319],
 [157, 24, 134, 19, 553, 252, 287, 373],
 [425, 128, 444, 592, 380, 16, 66, 336]]